# SubNav
menu:
  å…³äº: /2014/aboutme/
subnav:
  #github: "https://github.com/imfycc"
  follow: "https://app.follow.is/share/feeds/57360050735182873"
  jike: "https://web.okjike.com/u/5005922E-4A9D-4197-BE4D-82A6215D9C4C"
  xiaohongshu: "https://www.xiaohongshu.com/user/profile/5b9dd4c026b94a0001bda524"
  weibo-original: "http://weibo.com/u/5263249441"
  apple-email: "mailto:hufy3651@163.com"
  #zhihu: "https://www.zhihu.com/people/hu-yang-11-57/"
  #makers-union: "https://union.zhaodao.ai/#random"
  #sf: "https://segmentfault.com/u/youthink"
  #youthol: "http://www.youthol.cn"
  #rss: "/atom.xml"

author: æ–¹è¿çš„åšå®¢
description: å¤©é©¬è¡Œç©ºï¼Œçˆ±ç”Ÿæ´»ï¼Œçˆ±Coding

# SEO
seo_keywords: èƒ¡æ–¹è¿,å°çŒ¿å¤§åœ£,ç¼–ç¨‹,ç¨‹åºå‘˜,ä¸ªäººåšå®¢,Youthink,imfycc,Web
seo_description: å°çŒ¿å¤§åœ£çš„ä¸ªäººåšå®¢,èƒ¡æ–¹è¿çš„åšå®¢,ç¼–ç¨‹éšæƒ³

# åº•éƒ¨çš„å¤‡æ¡ˆä¿¡æ¯
copyright_date: 2013-2024
beian_info: èƒ¡æ–¹è¿çš„åšå®¢ é²ICPå¤‡15009509å·

favicon: "https://static.hufangyun.com/favicon.ico"

#ä½ çš„å¤´åƒurl
avatar: https://static.hufangyun.com/face-small.png

# é¦–é¡µå·¦ä¾§è¾¹æ èƒŒæ™¯å›¾ç‰‡
# å¯é…ç½®å¤šä¸ª éšæœºæŒ‘é€‰ä¸€å¼ 
leftBackground:
  - https://static.hufangyun.com/hexo/bg1.jpg
  - https://static.hufangyun.com/hexo/bg2.jpg
  - https://static.hufangyun.com/hexo/bg3.jpg
  - https://static.hufangyun.com/hexo/bg4.jpg
  - https://static.hufangyun.com/hexo/bg5.jpg
  - https://static.hufangyun.com/hexo/bg6.jpg

# å±•ç¤ºæ›´æ–°æ—¶é—´
display_updated: true

# Data statistics
baidu_analytics: true
baidu_analytics_code: 279edd956f5d814ddf08af30b654b4c6

#Comments
# https://github.com/gitalk/gitalk
gitalk: true
gitalk_clientID: 3b064dc018768ed172b8
gitalk_clientSecret: 403c6f397465f7fa14cfb02668011929102421d1
gitalk_repo: Youthink.github.io
gitalk_owner: Youthink
gitalk_admin: Youthink

console: true
console_color: '#6190e8'
console_config:
  - '\næ¬¢è¿è®¿é—® https://hufangyun.com ï¼Œå›´è§‚æˆ‘çš„åšå®¢(ã¥ï½¡â—•â€¿â€¿â—•ï½¡)ã¥ï¼\n'
  - '\næœ¬åšå®¢ä½¿ç”¨ %cHexo%c æ­å»ºï¼Œåšå®¢ä¸»é¢˜ä¸ºæœ¬äººå¼€å‘çš„ %chexo-themes-yearn%c ~~~ ğŸ‰ğŸ‰ğŸ‰ \n\næºç  https://github.com/imfycc/hexo-themes-yearn \n\nå¦‚æœå–œæ¬¢å¯ä»¥ star æ”¯æŒä¸€ä¸‹ â¤ï¸~\n'
  - '\næ‰«æä¸‹é¢çš„äºŒç»´ç ï¼Œåœ¨æ‰‹æœºä¸ŠæŸ¥çœ‹åšå®¢ï¼\n'
  - 'https://static.hufangyun.com/blog-url-qrcode-180-180.png'
  - '\n æƒ³çŸ¥é“è¿™ä¸ªæ•ˆæœå¦‚ä½•å®ç°çš„ï¼Ÿåšå®¢å†…æœç´¢ console å½©è›‹ ğŸš€ ï¼\n'


# é•¿æ—¶é—´æœªæ›´æ–°çš„åšæ–‡æ˜¾ç¤ºæé†’
overdue_auto_all: false
overdue_remind: æœ¬æ–‡æœ€åæ›´æ–°äº$dayå¤©å‰ï¼Œæ–‡ä¸­æ‰€æè¿°çš„ä¿¡æ¯å¯èƒ½å·²å‘ç”Ÿæ”¹å˜ã€‚
